
# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

readme = ''

setup(
    long_description=readme,
    name='qmldataset',
    version='0.1.0',
    description='Dataset for applying ML on quantum systems.',
    python_requires='==3.*,>=3.8.0',
    author='Rajib Chakravorty',
    author_email='4748396+rajibchakravorty@users.noreply.github.com',
    license='MIT',
    packages=[
        'qmldataset',
        'qmldataset.control_pulse',
        'qmldataset.noise_profiles',
        'qmldataset.system_layers',
        'qmldataset.utilities'],
    package_dir={"": "."},
    package_data={},
    install_requires=['pylint==2.*,>=2.10.1', 'pytest==6.*,>=6.2.4', 'qutip==4.*,>=4.6.2', 'tensorflow==2.*,>=2.6.0'],
)
